apiVersion: apps/v1
kind: Deployment
metadata:
  name: registration-app-deployment
  labels:
    app: registration-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: registration-app
  template:
    metadata:
      labels:
        app: registration-app
    spec:
      containers:
        - name: registration-app-container
          image: charvireddy/rego:latest        # <-- UPDATED IMAGE
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
